### PR TITLE
Two small bugfixes

### PR DESCRIPTION
**Pull request by ChrisLR**
These are the minor fixes I had to do to get the tests running.

### CODE REVIEW

**Review by jpalladino84 — COMMENTED** [review]
Nice! Thanks for the contribution! If you could just remove the extra whitespace from some of these files I will merge.

**Comment by ChrisLR** [comment]
Sorry about that! Didn't check my email until now.
If you're interested I could contribute more but I'd like if we could have
a discussion on what to do next and some design choices.
It would help me to not vomit ideas all over the code like I've been doing

> .>

**Comment by ChrisLR** [comment]
Also noticed I should've started on a new branch sooner, this pull request seems to have merged more than the two small bugfixes I intended to.

**Comment by jpalladino84** [comment]
No worries at all @arzhul! The code looked good and I tested it locally so I felt comfortable merging. 

Also please, contribute all you want! My email is jeff@palladino.me. Feel free to reach out directly and we can go over next steps.

**Pull request merged**
