### PR TITLE
Add primitive unit speed.

### PR DESCRIPTION
**Pull request by SzySteve**

### CODE REVIEW

**Comment by jpalladino84** [comment]
Hey @SzySteve get latest from master and rebase. I added a .gitignore file so we don't keep committing those .pyc files.

**Comment by SzySteve** [comment]
Yeah I was wondering about that but didn't realize it til I had committed

**Comment by jpalladino84** [comment]
Yup they get really annoying cause we will always conflict with each other. 

Also just a heads up I just submitted a PR that overhauls the code base. All of the code that was in Game.py is now handled in /managers/game_manager.py. Once you clean up the .pyc out of your PR go ahead and merge this and I will rebase it into my branch and merge my changes.

**Comment by SzySteve** [comment]
That should do it

**Pull request merged**
